name: Deploy

on:
  push:
    branches:
      - tests  # O la rama en la que trabajas

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Instalar Node.js y las dependencias
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Puedes cambiar la versión según sea necesario

      - name: Install dependencies
        run: |
          npm install

      # Paso 3: Construir el proyecto con Astro
      - name: Build project
        run: |
          npm run build  

      # Paso 4: Subir los archivos por FTP
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: './dist/'  # El directorio de salida de Astro
          server-dir: '/public_html'  # Directorio en Hostinger
